apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-advisor
spec:
  selector:
    matchLabels:
      app: game-advisor
  template:
    metadata:
      labels:
        app: game-advisor
    spec:
      serviceAccount: genkit
      containers:
      - name: game-advisor
        image: us-docker.pkg.dev/backlogged-ai/llm/game-advisor:v2.2.2
        resources:
          limits:
            memory: "4Gi"
            cpu: "2"
        env: 
        - name: OLLAMA_ADDRESS
          value: "http://ollama-service:8080"
        ports:
        - containerPort: 3400
          name: http
          protocol: TCP
        
---
apiVersion: v1
kind: Service
metadata:
  name: game-advisor
spec:
  selector:
    app: game-advisor
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 3400
    protocol: TCP
    name: http
